In [28]:
import numpy as np
from tensornetwork import ncon
A = np.array([[1.0, 2.0], [3.0, 4.0]])
B = np.array([[1.0, 1.0], [0.0, 1.0]])
X=ncon([A,B], [(-1, 1), (1, -2)])

In [30]:
X

array([[1., 3.],
       [3., 7.]])

In [33]:
np.einsum('ij,kl->il', A, B)

array([[ 3.,  6.],
       [ 7., 14.]])

In [40]:
np.ones((1)).shape

(1,)

In [39]:
np.ones((1, 5, 1))

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [41]:
sBA=np.ones((1))
sBA=np.diag(sBA)
#u, s_vals, v = svd(ncon([np.diag(sBA), A, np.diag(sAB), B, np.diag(sBA), gate], [[-1, 1], [1, 5, 2], [2, 4], [4, 6, 3], [3, -4], [5, -2, 6, -3]]).reshape([d1 * rank_BA, d2 * rank_BA]), full_matrices=False)

In [44]:
sBA.shape

(1, 1)

In [46]:
np.cumsum([1,2,3,4])

array([ 1,  3,  6, 10])